(()=>{
 const tr=document.documentElement.lang==='tr', key='hawan-cart-v1',assets=[4,2,1,3,5,6],woodKeys=['olive','walnut','cypress','cherry'];
 const t=tr?{cart:'Sepetin',choices:'SEÇİMLERİN',close:'Sepeti kapat',wood:'Malzeme',size:'Boyut',choose:'Malzeme seçin',add:'Sepete Ekle',remove:'Kaldır',less:'Adet azalt',more:'Adet artır',summary:'Sipariş özeti',count:'Toplam adet',subtotal:'Ara toplam',price:'Fiyat yakında',note:'Satış henüz açılmadı. Fiyat, kargo ve ödeme bilgileri satış başladığında burada gösterilecek.',pay:'Ödemeye Geç · Yakında',view:'Sepeti Görüntüle',continue:'Alışverişe devam et',empty:'Sepetin henüz boş.',explore:'Tasarımları keşfet',select:'Önce malzeme ve boyutunu seç.',saved:'Sepet güncellendi.',storage:'Sepetin bu tarayıcıda kalıcı olarak kaydedilemiyor.',approx:'Organik formlar nedeniyle boyutlar yaklaşık ölçülerdir.'}:{cart:'Your Cart',choices:'YOUR SELECTIONS',close:'Close cart',wood:'Material',size:'Size',choose:'Choose a material',add:'Add to Cart',remove:'Remove',less:'Decrease quantity',more:'Increase quantity',summary:'Order summary',count:'Total quantity',subtotal:'Subtotal',price:'Price coming soon',note:'Sales are not open yet. Prices, shipping and payment information will appear here when sales open.',pay:'Checkout · Coming Soon',view:'View Cart',continue:'Continue shopping',empty:'Your cart is empty.',explore:'Explore the designs',select:'Choose your material and size first.',saved:'Cart updated.',storage:'Your cart cannot be saved persistently in this browser.',approx:'Sizes are approximate due to the organic forms.'};
 const woods=tr?['Zeytin','Ceviz','Selvi','Kiraz']:['Olive','Walnut','Cypress','Cherry'],shop=tr?'/tr/magaza/':'/en/shop/',cartURL=tr?'/tr/sepet/':'/en/cart/',productURL=n=>`${tr?'/tr/urun/':'/en/product/'}hawan-no-${n}/`;
 function valid(items){if(!Array.isArray(items))return [];const result=[];for(const i of items.slice(0,500)){if(!i||!Number.isInteger(i.n)||i.n<1||i.n>6||!woodKeys.includes(i.wood)||!Number.isInteger(i.size)||i.size<17||i.size>25||!Number.isInteger(i.qty)||i.qty<1)continue;const prior=result.find(j=>j.n===i.n&&j.wood===i.wood&&j.size===i.size);if(prior)prior.qty=Math.min(99,prior.qty+i.qty);else result.push({n:i.n,wood:i.wood,size:i.size,qty:Math.min(99,i.qty)});}return result;}
 let memory=[],storageUnavailable=false;
 function read(){if(storageUnavailable)return valid(memory);try{return valid(JSON.parse(localStorage.getItem(key)||'[]'));}catch{return valid(memory);}}
 let items=read(),lastFocus,view='cart';
 const page=document.querySelector('[data-cart-page]'),dialog=document.createElement('dialog');dialog.className='hc hc-drawer';dialog.setAttribute('aria-labelledby','hc-dialog-title');document.body.append(dialog);
 const status=document.createElement('p');status.className='hc-status';status.setAttribute('role','status');document.body.append(status);
 const image=n=>`/assets/models/HAWAN-0${assets[n-1]}.png`;
 const count=()=>items.reduce((sum,i)=>sum+i.qty,0);
 function lines(){return items.length?items.map((i,index)=>`<article class="hc-item"><a href="${productURL(i.n)}"><img src="${image(i.n)}" alt="HAWAN No.${i.n}"></a><div><a href="${productURL(i.n)}" class="hc-name">HAWAN No.${i.n}</a><p>${woods[woodKeys.indexOf(i.wood)]} · ${i.size} cm</p><div class="hc-item-controls"><div class="hc-qty"><button type="button" data-action="minus" data-index="${index}" aria-label="HAWAN No.${i.n} — ${t.less}" ${i.qty===1?'disabled':''}>−</button><span>${i.qty}</span><button type="button" data-action="plus" data-index="${index}" aria-label="HAWAN No.${i.n} — ${t.more}" ${i.qty===99?'disabled':''}>+</button></div><button type="button" class="hc-remove" data-action="remove" data-index="${index}">${t.remove}</button></div></div></article>`).join(''):`<div class="hc-empty"><h2>${t.empty}</h2><a class="hc-solid" href="${shop}">${t.explore} ↗</a></div>`;}
 function summary(drawer){return `<aside class="hc-summary"><h2>${t.summary}</h2><p class="hc-total"><span>${t.count}</span><span>${count()}</span></p><p class="hc-total"><span>${t.subtotal}</span><span>${t.price}</span></p><p class="hc-note">${t.note}</p>${drawer?`<a class="hc-solid" href="${cartURL}">${t.view} ↗</a>`:`<button class="hc-solid" type="button" disabled>${t.pay}</button>`}${drawer?`<button type="button" class="hc-continue" data-close>${t.continue}</button>`:`<a class="hc-continue" href="${shop}">${t.continue}</a>`}</aside>`;}
 function content(drawer){return `<div class="hc-top"><div><span class="hc-eyebrow">${t.choices}</span><${drawer?'h2':'h1'} ${drawer?'id="hc-dialog-title"':''}>${t.cart}</${drawer?'h2':'h1'}></div>${drawer?`<button type="button" class="hc-close" data-close aria-label="${t.close}">×</button>`:''}</div><div class="hc-layout"><div>${lines()}</div>${items.length?summary(drawer):''}</div>`;}
 function render(){const total=count();document.querySelectorAll('[data-cart-count]').forEach(e=>{e.textContent=total>9?'+':total;e.closest('button').setAttribute('aria-label',`${t.cart} (${total})`);});if(page)page.innerHTML=content(false);if(view==='cart')dialog.innerHTML=content(true);}
 function save(){memory=valid(items);try{localStorage.setItem(key,JSON.stringify(items));storageUnavailable=false;status.textContent=t.saved;}catch{storageUnavailable=true;status.textContent=t.storage;}render();}
 function open(){lastFocus=document.activeElement;view='cart';items=read();render();dialog.showModal();}
 function close(){dialog.close();}
 dialog.addEventListener('close',()=>lastFocus?.focus());
 function add(n,wood,size){items=read();const existing=items.find(i=>i.n===n&&i.wood===wood&&i.size===size);if(existing)existing.qty=Math.min(99,existing.qty+1);else items.push({n,wood,size,qty:1});view='cart';save();if(!dialog.open){lastFocus=document.activeElement;dialog.showModal();}dialog.querySelector('[data-close]')?.focus();}
 function choose(n){lastFocus=document.activeElement;view='choose';dialog.innerHTML=`<div class="hc-top"><h2 id="hc-dialog-title">HAWAN No.${n}</h2><button type="button" class="hc-close" data-close aria-label="${t.close}">×</button></div><img class="hc-selection-image" src="${image(n)}" alt="HAWAN No.${n}"><p class="hc-note">${t.select}</p><form class="hc-options"><label>${t.wood}<select name="wood" required><option value="">${t.choose}</option>${woodKeys.map((w,i)=>`<option value="${w}">${woods[i]}</option>`).join('')}</select></label><label>${t.size}<select name="size">${Array.from({length:9},(_,j)=>`<option value="${j+17}">${j+17} cm</option>`).join('')}</select></label><p class="hc-note">${t.approx}</p><button class="hc-solid" type="submit">${t.add}</button></form>`;dialog.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(form.reportValidity())add(n,form.elements.wood.value,Number(form.elements.size.value));});dialog.showModal();}
 document.querySelectorAll('[data-cart-open]').forEach(b=>b.addEventListener('click',open));
 document.querySelectorAll('.model-cart').forEach(b=>{b.disabled=false;b.removeAttribute('title');b.addEventListener('click',()=>{const link=b.closest('.model-actions').querySelector('a').getAttribute('href');const match=link.match(/hawan-no-([1-6])/);if(match)choose(Number(match[1]));});});
 document.querySelectorAll('[data-product-add]').forEach(b=>b.addEventListener('click',()=>{const product=b.closest('[data-product]'),radios=product.querySelectorAll('[name="material"]');radios[0].required=true;const material=product.querySelector('[name="material"]:checked');if(!material){radios[0].reportValidity();radios[0].focus();return;}add(Number(product.dataset.product),material.value,Number(product.querySelector('[name="size"]').value));}));
 function controls(e){const closeButton=e.target.closest('[data-close]');if(closeButton){close();return;}const b=e.target.closest('[data-action]');if(!b)return;const index=Number(b.dataset.index),action=b.dataset.action;if(!items[index])return;if(action==='remove')items.splice(index,1);else items[index].qty=Math.max(1,Math.min(99,items[index].qty+(action==='plus'?1:-1)));save();const root=e.currentTarget;const next=root.querySelector(`[data-index="${Math.min(index,items.length-1)}"][data-action="${action}"]:not(:disabled)`)||root.querySelector('button:not(:disabled),a');next?.focus();}
 dialog.addEventListener('click',controls);page?.addEventListener('click',controls);
 dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();});
 window.addEventListener('storage',e=>{if(e.key===key||e.key===null){items=read();render();}});window.addEventListener('pageshow',()=>{items=read();render();});render();
})();
