const assets=[4,2,1,3,5,6],woods=['Zeytin','Ceviz','Selvi','Kiraz'];
const products=document.querySelector('.products'),dialog=document.querySelector('#cart');
let mode='drawer',cart=[];
const img=n=>`/assets/models/HAWAN-0${assets[n-1]}.png`;
products.innerHTML=assets.map((a,i)=>`<article class="product" data-product="${i+1}"><a class="product-image" href="/tr/urun/hawan-no-${i+1}/"><img src="${img(i+1)}" alt="HAWAN No.${i+1}" loading="lazy"></a><div class="number"><h3>HAWAN No.${i+1}</h3><span>0${i+1} / 06</span></div><p>Ahşap havan & tokmak</p><div class="choices"><label>Malzeme<select class="wood" aria-label="HAWAN No.${i+1} malzeme">${woods.map(w=>`<option>${w}</option>`).join('')}</select></label><label>Boyut<select class="size" aria-label="HAWAN No.${i+1} boyut">${Array.from({length:9},(_,j)=>`<option>${j+17} cm</option>`).join('')}</select></label></div><div class="actions"><a href="/tr/urun/hawan-no-${i+1}/">Ürünü İncele ↗</a><button class="add">Sepete Ekle +</button></div></article>`).join('');
function render(){const count=cart.reduce((sum,item)=>sum+item.qty,0);document.querySelectorAll('.count,.total-count').forEach(e=>e.textContent=count);document.querySelector('.cart-items').innerHTML=cart.length?cart.map((item,index)=>`<article class="cart-item"><img src="${img(item.n)}" alt="HAWAN No.${item.n}"><div><h3>HAWAN No.${item.n}</h3><p>${item.wood} · ${item.size}</p><div class="item-bottom"><div class="quantity"><button data-index="${index}" data-action="minus" aria-label="HAWAN No.${item.n} adet azalt">−</button><span>${item.qty}</span><button data-index="${index}" data-action="plus" aria-label="HAWAN No.${item.n} adet artır">+</button></div><button class="remove" data-index="${index}" data-action="remove">Kaldır</button></div></div></article>`).join(''):'<div class="empty">Yeni bir ritüele yer aç.<p>Sepetin henüz boş. Koleksiyondan bir tasarım seçebilirsin.</p></div>';document.querySelector('#status').textContent=`Sepette ${count} ürün var.`;}
function openCart(){render();dialog.className=mode;dialog.showModal();}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
products.addEventListener('click',e=>{const button=e.target.closest('.add');if(!button)return;const card=button.closest('.product'),n=Number(card.dataset.product),wood=card.querySelector('.wood').value,size=card.querySelector('.size').value;const existing=cart.find(i=>i.n===n&&i.wood===wood&&i.size===size);if(existing)existing.qty++;else cart.push({n,wood,size,qty:1});openCart();});
document.querySelector('.cart-open').addEventListener('click',openCart);
document.querySelector('.sample').addEventListener('click',()=>{if(!cart.length)cart=[{n:1,wood:'Zeytin',size:'17 cm',qty:1},{n:3,wood:'Ceviz',size:'21 cm',qty:1}];openCart();});
document.querySelectorAll('.close,.continue').forEach(b=>b.addEventListener('click',()=>dialog.close()));
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}const b=e.target.closest('[data-action]');if(!b)return;const i=Number(b.dataset.index),action=b.dataset.action;if(action==='remove')cart.splice(i,1);else if(action==='plus')cart[i].qty++;else if(cart[i].qty>1)cart[i].qty--;else cart.splice(i,1);render();const next=dialog.querySelector(`[data-index="${Math.min(i,cart.length-1)}"][data-action="${action}"]`)||dialog.querySelector('.close');next.focus();});
render();
